# Generated by Django 4.2.6 on 2023-10-29 03:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auctionlisting",
            name="date_ends",
            field=models.DateField(
                default=datetime.datetime(2023, 11, 4, 23, 34, 25, 213437)
            ),
        ),
    ]
