# Generated by Django 4.2.7 on 2023-12-02 07:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0003_alter_auctionlisting_date_ends"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auctionlisting",
            name="date_ends",
            field=models.DateField(
                default=datetime.datetime(2023, 12, 9, 2, 35, 57, 909073)
            ),
        ),
    ]
