# Generated by Django 4.2.5 on 2023-10-17 06:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0003_alter_auctionlisting_date_ends"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auctionlisting",
            name="date_ends",
            field=models.DateField(
                default=datetime.datetime(2023, 10, 24, 2, 5, 37, 605305)
            ),
        ),
    ]
