# Generated by Django 4.2.5 on 2023-12-03 08:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0004_alter_auctionlisting_date_ends"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auctionlisting",
            name="date_ends",
            field=models.DateField(
                default=datetime.datetime(2023, 12, 10, 3, 23, 56, 170809)
            ),
        ),
    ]
