# Generated by Django 4.2.5 on 2023-10-27 18:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0004_alter_auctionlisting_date_ends"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auctionlisting",
            name="date_ends",
            field=models.DateField(
                default=datetime.datetime(2023, 11, 3, 14, 21, 45, 376488)
            ),
        ),
    ]
