# Generated by Django 4.2.6 on 2023-10-28 18:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0005_alter_auctionlisting_date_ends"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auctionbid",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="auctioncomment",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="auctionlisting",
            name="date_ends",
            field=models.DateField(
                default=datetime.datetime(2023, 11, 4, 14, 8, 4, 731786)
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
